#!/usr/bin/env bash
# Function to handle SIGTERM signal

handle_sigterm() {
    echo "I am invincible!!!"
    exit 0
}

# Trap SIGTERM signal
trap 'handle_sigterm' SIGTERM

# Infinite loop with a 2-second sleep
while true; do
    echo "To infinity and beyond"
    sleep 2
done
