#!/usr/bin/env bash
# Initialize variables for hours and minutes
hour=1
minute=1

# Using a while loop to display time for 12 hours and 59 minutes
while [ $hour -le 12 ]
do
    echo "Hour: $hour"
    while [ $minute -lt 60 ]
    do
        echo "$minute"
        ((minute++))
    done
    minute=1
    ((hour++))
done

